kind: pipeline
type: kubernetes
name: Continuous Integration

trigger:
  branch:
    - main
  event:
    - pull_request
    - push

clone:
  disable: true

workspace:
  path: /go/src/github.com/${DRONE_REPO}

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://github.com/${DRONE_REPO}.git .
      - git checkout $DRONE_COMMIT

  - name: build_image
    image: plugins/ecr
    privileged: true
    depends_on:
      - clone
    settings:
      dockerfile: Dockerfile
      registry: 462204803675.dkr.ecr.us-east-1.amazonaws.com
      debug: true
      target: builder
      build_args:
        - CONEKTA_GP_TOKEN
        - CONEKTA_GP_USER
      tags:
        - ${DRONE_BUILD_NUMBER/\//-}
        - ${DRONE_SOURCE_BRANCH//\//-}
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      PLUGIN_SSH_AGENT_KEY:
        from_secret: SSH_KEY
      DOCKER_BUILDKIT: 1
      ECR_CREATE_REPOSITORY: true
      PLUGIN_REPO: ${DRONE_REPO}

  - name: tests
    image: 462204803675.dkr.ecr.us-east-1.amazonaws.com/${DRONE_REPO}:${DRONE_BUILD_NUMBER/\//-}
    commands:
      - make test
    depends_on:
      - build_image

image_pull_secrets:
  - DOCKERCONFIG
