language: go
sudo: false
go:
  - 1.12.4
  - 1.11.x
cache:
  directories:
    - vendor
install:
  - make build
script:
  - make test
  - go test github.com/nikunjy/rules/parser -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
