name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: aws-runner-set
    steps:
      - name: Checkout code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --build-arg CONEKTA_GP_TOKEN=${{ secrets.CONEKTA_GP_TOKEN }} \
            --build-arg CONEKTA_GP_USER=${{ secrets.CONEKTA_GP_USER }} \
            --target builder \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ github.repository }}:${{ github.run_id }} .

      - name: 📦 Install dependencies
        run: go mod tidy  && go mod download

      - name: 🧪 Run tests
        run: make test