name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  sonarqube:
    runs-on: aws-runner-set
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

  build:
    runs-on: aws-runner-set
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: ⓖⓞ Configure Python
        uses: actions/setup-go@v1
        with:
          go-version: 1.23

      - name: 📦 Install dependencies
        run: go mod tidy  && go mod download

      - name: 🧪 Run tests
        run: make test